; FasterEdge MCU (PIC10F200) — platformio_ide 版
; PlatformIO + microchippic 平台；PIC10F200 仅支持 MPASM 汇编。
; 使用：pio run -t upload && pio device monitor（无串口，仅编程）
[env:pic10f200]
platform = microchippic
board = pic10f200
monitor_speed = 9600
build_flags =
    -D__PIC10F200__
